version: "3.3"
services:
  traccar:
    container_name: traccar
    image: traccar/traccar:5.12-ubuntu
    restart: unless-stopped
    ports:
      - "8082"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traccar.tls=true"
      - "traefik.http.routers.traccar.tls.certresolver=myresolver"
      - "traefik.http.routers.traccar.rule=Host(`traccar.genialrastreamento.com.br`)"
    volumes:
      - ./logs:/opt/traccar/logs:rw
      - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro
   
    depends_on:
      - mysql
    networks:
      - "traefik"
      - "mysql"

  mysql:
    container_name: mysql
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_DATABASE: 'traccar'
      MYSQL_PASSWORD: 'traccar'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'traccar'
    ports:
      - "3306"
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
    networks:
      - mysql

networks:
  traefik:
    external: true
  mysql:
    external: true
