version: "3.3"
networks:
  traefik:
    external: true
services:
  traccar:
    image: traccar/traccar:5.12-ubuntu
    ports:
      - "8082"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traccar.tls=true"
      - "traefik.http.routers.traccar.tls.certresolver=myresolver"
      - "traefik.http.routers.traccar.rule=Host(`traccar.genialrastreamento.com.br`)"
    volumes:
      - ./logs:/opt/traccar/logs:rw
      - ./data:/opt/traccar/data:rw
      - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro
    networks:
      - "traefik"
