version: "3.3"

services:

  traccar:
    container_name: traccar
    image: traccar/traccar:5.12-ubuntu
    restart: unless-stopped
    ports:
      - "8082"
    volumes:
      - ./logs:/opt/traccar/logs
      - ./conf/traccar.xml:/opt/traccar/conf/traccar.xml:ro
    depends_on:
      - mysql
    networks:
      - "nginx"
      - "mysql"

  mysql:
    container_name: mysql
    image: 'mysql:latest'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'traccar'
      MYSQL_PASSWORD: 'traccar'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'traccar'
    ports:
      - "3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - mysql

networks:
  nginx:
    external: true
  mysql:
    external: true



